site_name: Cloud API
site_url: http://127.0.0.1:8001
site_description: Project Contain Clouds API.
site_author: ARB Team
repo_url: http://ncplgogs.clouzerindia.com:2495/
edit_uri: ""

nav:
    - Home: index.md
    - 'Appointment Wizard ':
      - Introduction: appointmentWizard/appointmentIntroduction.md
      - Manage Appointment (Sales) : appointmentWizard/saleMainAppointment/SalesMainAppointment(TSK_MAPT).md
      - Builder Appointment (Purchase/Own): appointmentWizard/purchaseMainAppointment/purchaseMainAppointment.md
    - Property Wizard  :
      - Introduction:      propertyWizard/propertyIntroduction.md
      - Property Listing:  propertyWizard/propertyListing/propertyListing.md
      - Property Project:  propertyWizard/propertyProject/propertyProject.md


theme:
  palette:
    primary: indigo
    accent: light blue
  name: material
  favicon: img/favicon.png
  features:
    - instant
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
